# hydra config for class same as file name:
_target_: modelflow.command.Sequence
tasks_list: # tasks are all in sequence
  - _target_: modelflow.run.LayerExchange
    cmd_args: "run=train dataset=tsV2 dataset.dataloader.batch_size=2 tokenizer=hf tokenizer.encoding=fhswf/BPE_GPT2_TinyStoriesV2_cleaned_2048 run.epochs=1 tokenizer=hf_gptneo +model.type=CHECKPOINT  model=NEW_BENCH2 quantization=qat quantization/model=NEW_BENCH2b run.export=True"
    source_layer: ""
    targer_layer: ""
    # all output functions get executed in sequence, make sure dependend variables are in proper order
    outputs:
      - _target_: modelflow.command.Output
        command: ${....0._target_}
        source:
          _target_: modelflow.command.StdoutSource
          re: "[INFO] - Run ID: <....>"
        goals:
        - _target_: modelflow.command.StoreVariableGoal
          key: "run_id"
          # value: same as value of source by default

      - _target_: modelflow.command.Output
        source:
          _target_: modelflow.command.FilePathSource
          path: "qtransform/chkpts/{{run_id}}.chkpt"
          # returns path of file by default not content (FilePathSource not FileContentSource!)
        goals:
        - _target_: modelflow.command.FileCopyGoal
          location: "modelflow/{{run_id}}"
        - _target_: modelflow.command.StoreVariableGoal
          key: "chkpt-{{run_id}}"
          # value: path of file