command: train

always_save_checkpoint : True # if True, always save a checkpoint after each eval
# model_chkpt_dir: ${oc.env:HOME}
checkpoint_dir: models
epochs: 10
gradient_accumulation_steps : 5 * 8 # used to simulate larger batch sizes, leave empty for no accumulation
flash: False
export: True ## perform an export after #epochs are done
max_iters : 600000 # total number of training iterations for one epoch
save_epoch_interval: 1
log_steps_interval : 10
grad_clip : 0.7 # clip gradients at this value, or disable if :: 0.0

eval_epoch_interval : 1000 #perform eval after specified amount of epochs
eval_iters: 200 #retrieve specified amount of batches for evaluation

#moved optimizer stuff (lr, optimizer class, lr decay) to qtransform.optim

# export params are loaded from export.yaml