hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  #verbose: [__main__] # only for hydra debug logging, otherwise use debug=True
  searchpath:
    - pkg://qtransform
defaults:
  - _self_
  - model: gpt_2_small
  - dataset: openwebtext
  - run: ???
  - override hydra/job_logging: custom
  - override hydra/help: main

  #- override hydra/job_logging: colorlog
  #- override hydra/hydra_logging: colorlog

data:  
  dtype: 'bfloat16' # 'float32', 'bfloat16', or 'float16'
device : 'cuda'
debug: False

seed: 1234567890
# DDP settings
#backend : 'nccl' # 'nccl', 'gloo', etc.
