hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  #verbose: [__main__] # only for hydra debug logging, otherwise use debug=True
  searchpath:
    - pkg://qtransform
defaults:
  - _self_
  - model: gpt_2_small
  - dataset: openwebtext
  - optim: default
  - run: ???
  - override hydra/job_logging: custom
  - override hydra/help: main
  #- override hydra/job_logging: colorlog
  #- override hydra/hydra_logging: colorlog

data:  
  dtype: 'bfloat16' # 'float32', 'bfloat16', or 'float16'. if llm is used, np dtypes are necessary
device : 'cuda'
debug: False

dataset:
  wrapper: ??? #name of dataset wrapper to use which returns an instance of type Dataset
  root_path: ~/.qtransform/cache
  #points to the directory containing the dataset used for training/validation etc. 
  #the list is composed of subentries under root_path (root_path included) in hierarchical order
  #the filename of the dataset is not included as it could be split into multiple files (take MNIST for example)
  dataset_dir: 
    - ${dataset.root_path}
    - data
    - ${dataset.name}
seed: 1234567890
# DDP settings
#backend : 'nccl' # 'nccl', 'gloo', etc.
