# learning rate decay settings
decay_lr : True # whether to decay the learning rate. uses torch.optim.lr_scheduler schedulers
scheduler: StepLR
warmup_iters : 2000 # how many steps to warm up for
args:
  lr_decay_iters : 600000 # should be ~: max_iters per Chinchilla
  min_lr : 6e-5 # minimum learning rate, should be ~: learning_rate/10 per Chinchilla
  step_size: 1